#!/bin/sh

[ "$1" ] || exit 1
[ -f "$1" ] || exit 2

PGM=`basename "$0"`
TMP="/tmp/$PGM"
casting="$1"
cat "$casting" | grep "_(" | cut -d "(" -f 2 | cut -d ")" -f 1 | sort -u | while read role
do
	mkdir -p "$role"
	echo "<?php" > "$TMP.$role"
	echo "\$customnames=array(" >> "$TMP.$role"
	touch "$TMP.$role"
	grep "($role)" "$casting" | while read line
	do
		name=`echo "$line" | cut -d "\"" -f 2 | sed "s/_(.*//" | sed "s/.*\///"`
		egrep "[0-9]-$name" "$TMP.$role" >/dev/null 
		if [ ! $? -eq 0 ]
			then
			egrep "[0-9]-$name" "$casting" >> "$TMP.$role"
		fi
		printf "\t$line\n" >> "$TMP.$role"
	done
	printf ");\n" >> "$TMP.$role"
	printf "?>" >> "$TMP.$role"
	cat "$TMP.$role" >> "$role/playlist.php"
	echo
done
