#!/bin/sh

PGM=`basename "$0" .sh`
PENDING="$PWD/.$PGM-pending"
REMOTE=bingo@duke:www/bingofamily.be/manu/base/.streetcasting

mkdir -p ../web || exit 1

touch "$PENDING"

echo "## fetching last movies"

ls *.mp4 2>/dev/null | while read file
	do
	newfile=`echo "$file" | sed "s/-MPEG4.*/.mp4/"`
	mv "$file" "../web/$newfile" \
		&& qt-thumbnails.sh "../web/$newfile" \
		&& touch "$PENDING"
	done

cd ../web

LOCAL=$PWD

#echo "## building playlist"


#(
#	echo "<?php"
#	echo "\$customnames=array("
#	ls *.mp4 | egrep "[, ]" \
#		| while read file
#		do
#			echo "\"$file\" => '`basename "$file" .mp4|sed "s/^[0-9 -]*//"`',"
#		done 
#	echo "\"title1\" => '&nbsp;',"
#	ls *.mp4 | egrep -v "[ ,]" \
#		| while read file
#		do
#		echo "\"$file\" => '`basename "$file" .mp4|sed "s/^[0-9 -]*//"`',"
#	done
#	echo ");"
#	echo "?>" 
#) > playlist.php

ps -awwx | grep -v grep | grep rsync >/dev/null

if [ $? -eq 0 ]
	then
	echo "## sync delayed because a transfert is already in progress"
	exit
fi

while [ -f "$PENDING" ]
	do
	rm "$PENDING"

	echo "## sending light files"
	rsync --exclude "*.mp4" --progress -Wavz \
		--exclude ".DS*" --exclude "disabled" \
		"$LOCAL/" \
		$REMOTE

	echo "## sending movies"
	rsync --progress -Wavz --exclude ".DS*" \
		--exclude "disabled" \
		"$LOCAL/" \
		$REMOTE
		
	echo "## checking pending jobs"
done