#!/bin/sh

PGM=`basename $0`
BUFUSER=$PGM

if [ -f ~/.$PGM.conf ]
then
	. ~/.$PGM.conf
elif [ -f /etc/$PGM.conf ]
then
	. /etc/$PGM.conf
else
	echo "$PGM: no config file - request not processed"
	exit 1
fi

if [ "`whoami`" != "$OWNER"  ]
then
	PREFIX="sudo -u $OWNER"
fi

cd ~$OWNER/
echo $PWD


$PREFIX sitecopy -r ~$OWNER/.sitecopyrc -p ~$OWNER/.sitecopy -ll ondex_prev
