#!/bin/sh

PGM=`basename "$0" .sh`
PENDING="$PWD/.$PGM-pending"
LOCAL=/Users/magic/Jobs/deux-huit/sfr
REMOTE=deuxhuit@deuxhuit.be:www/deuxhuit.be/sfr
EXCLUDE='--exclude "qt-thumbnails*" --exclude ".DS*" --exclude "disabled"'

echo "$PENDING"
touch "$PENDING"

echo "## fetching last movies"

ls *-MPEG4*.mp4 2>/dev/null | while read file
	do
	newfile=`echo "$file" | sed "s/-MPEG4.*/.mp4/"`
	mv "$file" "../web/$newfile" \
		&& qt-thumbnails.sh "../web/$newfile" 2>/dev/null \
	touch "$PENDING"
	done

cd ../web

cd "$LOCAL"

#ls | while read folder
#	do 
#	qt-thumbnails.sh $folder/*.mp4
#done

#echo "## building playlist"


#(
#	echo "<?php"
#	echo "\$customnames=array("
#	ls *.mp4 | egrep "[, ]" \
#		| while read file
#		do
#			echo "\"$file\" => '`basename "$file" .mp4|sed "s/^[0-9 -]*//"`',"
#		done 
#	echo "\"title1\" => '&nbsp;',"
#	ls *.mp4 | egrep -v "[ ,]" \
#		| while read file
#		do
#		echo "\"$file\" => '`basename "$file" .mp4|sed "s/^[0-9 -]*//"`',"
#	done
#	echo ");"
#	echo "?>" 
#) > playlist.php

ps -awwx | grep -v grep | grep rsync >/dev/null

if [ $? -eq 0 ]
	then
	echo "## sync delayed because a transfert is already in progress"
	echo
	echo "rsync --exclude \"*.mp4\" --progress -Wavz $EXCLUDE $LOCAL/ $REMOTE/"
	echo "rsync --progress -Wavz $EXCLUDE $LOCAL/ $REMOTE/"
	exit
fi

while [ -f "$PENDING" ]
	do
	rm "$PENDING"
	~/bin/casting-batch-splitlist >/dev/null
	echo "## sending light files"
	rsync --exclude "*.mp4" --progress -Wavz \
		$EXCLUDE \
		$LOCAL/ \
		$REMOTE/

	echo "## sending movies"
	rsync --progress -Wavz --exclude ".DS*" \
		$EXCLUDE \
		$LOCAL/ \
		$REMOTE/
		
	echo "## checking pending jobs"
done