#!/bin/sh

for folder in "$@"
do
	find $folder -iname "*.jpeg" | while read file
	do
		mv "$file" "${file/\.jpeg/.jpg}" \
		&& echo mv "$file" "${file/\.jpeg/.jpg}"
	
	done
	find $folder -name "*.JPG" | while read file
	do
		mv "$file" "${file/\.JPG/.jpg}" \
		&& echo mv "$file" "${file/\.JPG/.jpg}"
		
	done
	find $folder -iname "_*.jpg" | while read file
	do
		mv "$file" "${file/_/}" \
		&& echo mv "$file" "${file/_/}"
	done
done
