#!/bin/sh
#
# Copyright 2015 Olivier van Helden <olivier@van-helden.net>
# Released under GNU Affero GPL v3.0 license
#    http://www.gnu.org/licenses/agpl-3.0.html

PID=$$
[ "$PGM" ] || PGM=`basename $0`
[ "$TMP" ] || TMP=/tmp/$PGM.$PID
SPC=$(echo "$PGM" | sed "s/./ /g")
LOG=$TMP.log
DATA="$HOME/.$PGM"

COLOR_HIGHLIGHT="[1;31;40m"
COLOR_NORMAL="[0;;m"
[ ! "$ENDSUCCESS" ] && ENDSUCCESS="Succeed"
[ ! "$ENDFAILED" ] && ENDFAILED="Failed"

if [ "$USETTS" = "yes" ]
then
    SAY=$(which tts) || SAY=$(which say) || SAY=$(which espeak) || unset SAY
    echo "$SAY" | grep -q "/espeak$" && SAY="$SAY -v fr"
else
    SAY=echo
fi

BINDIR=$(dirname "$0")
BASEDIR=$(dirname "$BINDIR")
PATH=$BINDIR:$PATH

help() {
	echo "$PGM help"
	echo "$HELP"
}

USAGE="$PGM $SYNTAX"
usage() {
	echo "usage: $USAGE"
}

log() {
	[ "$1" ] || return
	if [ "$LOG" ]
		then
		ERRNUM=`echo "$@" |grep "^[0-9]* "|cut -d " " -f 1`
		ERR=`echo $ERRNUM|sed "s/\([0-9]*\)/<\\1\> /"`
		[ "$ERRNUM" ] && shift
		LOGMESSAGE=$@
		LOGLINE=`date +"%b %e %H:%M:%S"`" $PGM[$$]: $ERR$LOGMESSAGE"
		[ "$LOGGING" = "yes" ] && (echo $LOGLINE >> $LOG)
		if [ "$ERRNUM" ] 
			then
			echo "${COLOR_HIGHLIGHT}$PGM:${COLOR_NORMAL} $LOGMESSAGE" >&2 
			[ "$USETTS" = "yes" ] && $SAY "Error $ERRNUM: $LOGMESSAGE" 2>/dev/null &
		elif [ "$DEBUG" = "yes"  ]
			then
			# [ "$USETTS" = "yes" ] && $SAY "$LOGMESSAGE" &
			echo "$PGM: $LOGMESSAGE" >&2
		fi
	else
		echo "LOG variable not set"
		exit 1
	fi
}

end() {
	if [ "$1" ]
		then
		expr $1 + 0 >/dev/null 2>/dev/null && ERRNUM=$1 || ERRNUM=0
	else
		ERRNUM=0
	fi

	if [ "$ERRNUM" -ne 0 ]
		then
		# ERRNUM=`expr $ERRNUM + 0`
		shift
		[ "$#" -gt 0 ] && endMessage="$@" || endMessage=$ENDFAILED
		log $ERRNUM "$endMessage"
	else
		ERRNUM=0
		[ "$1" = "0" ] && shift
		[ "$#" -gt 0 ] && endMessage="$@" || endMessage=$ENDSUCCESS
		log "$endMessage"
		[ "$USETTS" = "yes" ] && $SAY "$endMessage" 2>/dev/null &
	fi

	rm -f $TMP*
	rm -f $LOG.lock
	# [ -f $LOG ] && chmod -f 666 $LOG*

	exit $ERRNUM
}

readvar() {
    for var in $@
    do
	varname=$(echo $var | sed "s/\([a-z]\)\([A-Z]\)/\\1 \\2/g")
	if [ "$AUTOMATIC" = "yes" ]
	then
	    echo "$varname: ${!var}"
	else
	    read -e -p "$varname: " -i ${!var} $var
	fi
    done
}

yesno() {
    default=n
    choice="y/N"
    [ "$1" = "y" ] && default=y && choice="Y/n" && shift
    [ "$@" ] && message="$@" || message="Answer"
    message="$message ($choice) "
    read -p "$message" answer
    [ "$answer" = "" ] && answer=$default
    answer=$(echo "$answer" | tr "[:upper:]" "[:lower:]")
    [ "$answer" = "y" ] && return 0
    [ "$answer" = "yes" ] && return 0
    return 1
}

ucfirst() {
    upper=$(echo $@ | cut -c 1 | tr "[:lower:]" "[:upper:]")
    lower=$(echo $@ | cut -c 2- | tr "[:upper:]" "[:lower:]")
    echo "$upper$lower"
}
