#!/bin/bash
#
# Copyright 2015 Olivier van Helden <olivier@van-helden.net>
# Released under GNU Affero GPL v3.0 license
#    http://www.gnu.org/licenses/agpl-3.0.html

# Parses .ini files and load values in bash
#
# LOAD VALUES:
# Put this line in your script, before the first use:
# (pay attention to the dot, do not execute parse directly)
#     . /PATH/TO/ini_parse
# Then, initiate an ini file
#     ini.parse /PATH/TO/YOUR.ini
# And to fetch values in SECTION
#     ini.section.SECTION
# You can repeat ini.parse and ini.section.*
# Values already present will be replaced
#
# WRITE VALUES:
# To output loaded values in .ini format:
#     ini.write
# To write only a specific section's values:
#     ini.section.SECTION
#     ini.write SECTION
# To output a new .ini file (including modified values):
#     ini.write.all
#         to output all sections, or
#     ini.write SECTION
#
# MERGE VALUES
# Load values of a section from serveral ini files
#     ini.merge SECTION FILE1 FILE2 [FILE3..]
#     Files are loaded in order provided, overriding previous values
#     Values not defined in next file are kept
#
# LIST SECTIONS
# List sections existing in given ini file(s)
#     ini.list.sections <file1.ini> [<file2.ini>] [...]

[[ $_ = $0 ]] && echo "$0 must be sourced, not run directly" && exit 1

shopt -s compat42
[ ! "$TAB" ] && TAB="   "
[ ! "$TMP" ] && TMP=/tmp/$(basename "0" | sed "s/ /_/g").$$
TMPINI=$TMP.ini_parser

trap "{ rm -f $TMPINI.*; ls $TMPINI.* 2>/dev/null; }" EXIT

ini.parse ()
{
    [ ! -f "$1" ] && log 1 "usage: $FUNCNAME <file.ini>" && return 1
    SAVED_IFS=$IFS
    # ini="$(<$1)"                # read the file
    ini=$(cat $1 \
	| sed "s/[[:blank:]]*=[[:blank:]]*/=/g" \
	| sed "s/^[[:blank:]]*;.*//" \
	| sed "s/;[[:blank:]]*$//" \
	| sed "s/;/%%SEMICOLON%%/g" \
	| egrep -v "^[[:blank:]]*;//" \
	| sed "s/^[[:blank:]]*$//" \
	| sed "s/\([{\\$]\)/\\\\\1/g" \
	| sed "s/=\([^\"].*[|{}\\$].*\)\"*$/=\"\\1\"/g" \
	| sed "s/=/%3D/g" \
	| sed "s/%3D/=/"
    )
    ini="${ini//[/\[}"          # escape [
    ini="${ini//]/\]}"          # escape ]
    IFS=$'\n' && ini=( ${ini} ) # convert to line-array
    ini=( ${ini[*]//;*/} )      # remove comments with ;
    ini=( ${ini[*]/\    =/=} )  # remove tabs before =
    ini=( ${ini[*]/=\   /=} )   # remove tabs after =
    ini=( ${ini[*]/\ =\ /=} )   # remove anything with a space around =
    ini=( ${ini[*]/#\\[/\}$'\n'ini.section.} ) # set section prefix
    ini=( ${ini[*]/%\\]/ \(} )    # convert text2function (1)
    ini=( ${ini[*]/=/=\(} )    # convert item to array
    ini=( ${ini[*]/%/ \)} )     # close array parenthesis
    ini=( ${ini[*]/%\\ \)/ \\} ) # the multiline trick
    ini=( ${ini[*]/%\( \)/\(\) \{} ) # convert text2function (2)
    ini=( ${ini[*]/%\} \)/\}} ) # remove extra parenthesis
    ini[0]="" # remove first element
    ini[${#ini[*]} + 1]='}'    # add the last brace
    eval "$(echo "${ini[*]}" \
            | sed -e 's/\\$\\{/\\\${/g' \
              -e 's/%%SEMICOLON%%/;/g' \
              -e 's/%3B/;/g' \
              -e 's/%3D/=/g'
           )"
    ini_cache=$1
    ini_parsed=$1
    IFS=$OLDIFS
}

ini.list.sections () 
{
    [ ! "$1" -a ! "$ini_parsed" ] && end 1 "$FUNCNAME needs you to load one or more .ini before using $FUNCNAME or supply files to load to the command"

    if [ "$1" ]
    then
	ini_process=$@
    else
	ini_process=$ini_parsed
    fi
    printf "" > $TMPINI.sections
    IFS=" "
    i=0
    touch $TMPINI.sections
    for file in $ini_process
    do
	[ ! -f "$file" ] && log 1 "$FUNCNAME $file not found" && continue
	i=$(($i + 1))
	printf "" | cat $file \
	    | grep "^[[:blank:]]*\[[a-zA-Z0-9_]*\]" \
	    | sed "s/;.*//" \
	    | cut -d "[" -f 2 | cut -d "]" -f 1 \
	    | while read section
	do
	    touch $TMPINI.sections.new $TMPINI.sections.added
	    grep -q "^$section$" $TMPINI.sections \
		&& continue
	    grep -q "^$section$" $TMPINI.sections.added \
		&& continue
	    echo $section >> $TMPINI.sections.added
	done
	cat $TMPINI.sections.added $TMPINI.sections > $TMPINI.sections.new 
	mv $TMPINI.sections.new $TMPINI.sections
	rm -f $TMPINI.sections.added
    done
    cat $TMPINI.sections
    rm -f $TMPINI.sections
    return
}

ini.write ()
{
    [ "$1" = "-a" ] && APPEND=yes && shift || unset APPEND
    SAVED_IFS=$IFS
    IFS=' '$'\n'
    fun="$(declare -F)"
    fun="${fun//declare -f/}"
    for f in $fun; do
        [ "${f#ini.section}" == "${f}" ] && continue
	[ "$1" ] && [ "$f" != "ini.section.$1" ] && continue
#        item="$(declare -f ${f})"
        item="$(declare -f ${f} | sed -e 's/\\${.*}/BRACE/g' -e "s/=/%3D/g" -e "s/%3D/=/")"
        item="${item##*[^\\]\{}"
        item="${item%\}}"
#        item="${item//=*;/}"
#        vars="${item//=*/}"
 	vars="$item"
        [ ! "$APPEND" ] && echo "[${f#ini.section.}]"
	for var in $vars; do
	    echo "$var" | grep -q "=" || continue
	    var=$(echo $var | sed -e "s/=/%3D/g" -e "s/%3D/=/") 
	    var="${var%=*}"
            echo "$TAB"$var=\"${!var}\" | grep -v ');*=""'
        done | sed 's/${/$\\{/g' > $TMPINI.vars
	eval $f
	. $TMPINI.vars
	rm -f $TMPINI.vars
        for var in $vars; do
	    echo "$var" | grep -q "=" || continue
	    var="${var%=*}"
            echo "$TAB"$var = \"${!var}\" | grep -v ');*=""'
        done | sed "s/\$\\\{/$\{/"
    done
    IFS=$SAVED_IFS
}

ini.merge()
{
    [ ! "$2" ] && log 1 "Usage: $FUNCNAME Section <file1.ini> [<file2.ini>] [...]" && return 1
    section=$1; shift
    ini.list.sections $@ | grep -q "^$section$"
    if [ $? -ne 0 ]
    then
	log 1 "$FUNCNAME didn't find the section $section"
	log 1 "Usage: $FUNCNAME Section <file1.ini> [<file2.ini>] [...]"
	return 1
    fi

    echo "[$section]" > $TMPINI.merge
    i=0
    for file in $@
    do
	i=$(($i + 1))
#	touch $TMPINI.merge.$i
	[ ! -f "$file" ] && continue
	
	ini.parse $file 2>/dev/null
	ini.list.sections $file | grep -q "^$section$" || continue
	ini.section.$section || continue
	ini.write -a $section | while read line
	do
	    var=$(echo "$line" | cut -d = -f 1 \
		| sed "s/[[:blank:]]*//g")
	    egrep -v "^[[:blank:]]*$var[[:blank:]]*=" $TMPINI.merge > $TMPINI.merge.new
	    echo "$line" >> $TMPINI.merge.new
	    mv $TMPINI.merge.new $TMPINI.merge
	done
    done
    count=$(cat $TMPINI.merge | wc -l)
    [ $count -gt 1 ] &&
    ini.parse $TMPINI.merge && ini_parsed="$@"*
    rm -f $TMPINI.merge.*
    return
}

ini.write.all ()
{
    [ ! "$1" ] && [ ! "$ini_parsed" ] && end 1 "$FUNCNAME needs you to load one or more .ini before using write.all or supply files to load to the command"
    if [ "$1" -a "$1" != "$ini_parsed" ]
    then
	ini.parse $@
	ini.write.all $@
	return
#    else
#	ini_process=$ini_parsed
    fi
    ini.list.sections "$@" | while read section
    do
	ini.merge $section $@
	ini.write $section
    done
}
