#!/bin/sh

LOCAL=/Volumes/Terra2/Irene/Peugeot/web
REMOTE=duke:data/www/magiiic.co.uk/peugeot/90ans
EXCLUDE='--exclude .qmsubexp --exclude "qt-thumbnails*" --exclude ".DS*" --exclude "disabled"'
SUFFIX="-MPEG4_680kpbs_480x360"
EXTENSION="mp4"
NEWEXT="mp4"
NEWSUF=""

PGM=`basename "$0" .sh`
TMP="/tmp/$PGM"


PENDING="${PWD}/.${PGM}-pending"
echo "$PENDING"
touch "$PENDING"

echo "## fetching last movies"

ls *${SUFFIX}.${EXTENSION} 2>/dev/null > "$TMP.list"
#sleep 10

cat "$TMP.list" | while read file
	do
	newfile=`echo "$file" | sed "s/${SUFFIX}.*/${NEWSUF}.${NEWEXT}/"`
	if [ ! -f "${file}TEMP"* ]
		then
			mv "$file" "../web/$newfile" \
				&& qt-thumbnails.sh "../web/$newfile" 2>/dev/null 
#			open -a "casse-flv" "../web/$newfile"
			touch "$PENDING"
		else
			echo "$file waiting"
	fi
	done

rm "$TMP.list"

cd ../web

cd "$LOCAL"

ls | while read folder
	do 
	if [ -d "$folder" ]
		then
		qt-thumbnails.sh -10 $folder/*.${NEWEXT}
	fi
done

#echo "## building playlist"


#(
#	echo "<?php"
#	echo "\$customnames=array("
#	ls *.mp4 | egrep "[, ]" \
#		| while read file
#		do
#			echo "\"$file\" => '`basename "$file" .mp4|sed "s/^[0-9 -]*//"`',"
#		done 
#	echo "\"title1\" => '&nbsp;',"
#	ls *.mp4 | egrep -v "[ ,]" \
#		| while read file
#		do
#		echo "\"$file\" => '`basename "$file" .mp4|sed "s/^[0-9 -]*//"`',"
#	done
#	echo ");"
#	echo "?>" 
#) > playlist.php


ps -awwx | grep -v grep | grep rsync >/dev/null

if [ $? -eq 0 ]
	then
	echo "## sync delayed because a transfert is already in progress"
	exit
fi


while [ -f "$PENDING" ]
	do
	rm "$PENDING"
#	~/bin/casting-batch-splitlist >/dev/null
	echo "## sending light files"
	rsync --progress -Wavz --exclude "*.${NEWEXT}" \
		$EXCLUDE \
		"$LOCAL/" \
		"$REMOTE/"

	echo "## sending movies"
	rsync --progress -Wavz \
		$EXCLUDE \
		"$LOCAL/" \
		"$REMOTE/"
		
	echo "## checking pending jobs"
done

