#!/bin/sh
#
# Opens isql connection with l/p found in ~/.isqlrc and send it stdin
#
# ~/.isqlrc file is formatted as follow:
# <DSQUERY> <USER> <PASSWORD>
# and MUST have mode 600
#
# ovh 24/11/2002: Added options to send result by mail

PGM=`basename $0`
TMP=$HOME/.$PGM.$$

RC=$HOME/.isqlrc

chmod 600 $RC || exit 1
touch $TMP || exit 2
BEGIN=`date`
for par in $@
do
	if [ -f "$par" ]
	then
		FILES="$FILES $par"
		PGMS="$PGMS `basename $par`"
	else
		MAILS="$MAILS $par"
	fi
done

(cat $FILES; echo "go") > $TMP

(
grep $DSQUERY $RC |head -1|while read dsquery dsuser dspass foo
do
  (echo $dspass; cat $TMP ) | isql -U $dsuser -S $dsquery -w 1000
done
) | tee $TMP.output

if [ "$MAILS" ]
then
	(
	echo "Output of isql batch(es)"; echo "Pwd:   $PWD"; echo
	for file in $FILES
	do
		echo "File:  $file"
		echo "Begin: $BEGIN"
		echo "End:   `date`"
		echo
	done
	cat $TMP.output|grep -v "^Password:" 
	) | /opt/clpb/bin/mail-report "[$HOSTNAME:$PGM] `basename $PGMS` results" $MAILS
fi

rm -f $TMP*
