#!/bin/sh

SOURCEDIR=/Users/magic/Jobs/julianne/website/juliannedeville.net/draft
DESTINATION=lesjulians@duke:www/juliannedeville.net/draft

PGM=`basename "$0" .sh`
echo "$PGM"
exit
PENDING="$PWD/.$PGM-pending"

touch "$PENDING"

echo "## fetching last movies"

ls *.mp4 *.flv 2>/dev/null | while read file
	do
	newfile=`echo "$file" | sed "s/-MPEG4.*/.mp4/" | sed "s/-FLV.*/.flv/"`
	sleep 10
	mv "$file" "$SOURCEDIR/$newfile" \
		&& qt-thumbnails.sh "$SOURCEDIR/$newfile" \
		&& touch "$PENDING"
	done

cd "$SOURCEDIR"

#echo "## building playlist"


#(
#	echo "<?php"
#	echo "\$customnames=array("
#	ls *.mp4 | egrep "[, ]" \
#		| while read file
#		do
#			echo "\"$file\" => '`basename "$file" .mp4|sed "s/^[0-9 -]*//"`',"
#		done 
#	echo "\"title1\" => '&nbsp;',"
#	ls *.mp4 | egrep -v "[ ,]" \
#		| while read file
#		do
#		echo "\"$file\" => '`basename "$file" .mp4|sed "s/^[0-9 -]*//"`',"
#	done
#	echo ");"
#	echo "?>" 
#) > playlist.php

ps -awwx | grep -v grep | grep rsync >/dev/null

if [ $? -eq 0 ]
	then
	echo "## sync delayed because a transfert is already in progress"
	exit
fi

while [ -f "$PENDING" ]
	do
	rm "$PENDING"

	echo "## sending light files"
	rsync --exclude "*.mp4" --exclude "*.flv" --progress -Wavz \
		--exclude ".DS*" --exclude "disabled" \
		"$SOURCEDIR/" \
		"$DESTINATION/"

	echo "## sending movies"
	rsync --progress -Wavz --exclude ".DS*" \
		--exclude "disabled" \
		"$SOURCEDIR/" \
		"$DESTINATION/"
		
	echo "## checking pending jobs"
done

echo "## nothing left to do, exiting"
