#!/bin/sh

remote=dave:www/magiiic.co.uk/karim
localbase=/Volumes/Castagne/2sur2/rubson/karim
folder="Rubson 2011"

PGM=`basename "$0"`
TMP=/tmp/$PGM

rsync -Pavz "$remote/" "$localbase/" | tee $TMP.syncresult
cat $TMP.syncresult | grep -B 1000 "^sent "| grep -v "^sent"| grep "/"|grep -v xfer > "$TMP.in-use"

ls "$localbase/$folder" | while read file
do
	printf "$file "
	grep "$file" "$TMP.in-use" 
	if [ $? -eq 0 ]
		then
		echo "still transfering" 
		continue
	fi
	newfile=`titlecase "$file" | sed "s/\.Mp4/.mp4/"`
	if [ -f "$newfile" ]
		then
		echo "exists"
		continue
	fi
	cp -p "$localbase/$folder/$file" "$newfile" && printf "copied " || continue
	open -a "MPEG4_700kpbs_480x360" "$newfile" && printf "compression launched " || continue
	echo
done
