#!/bin/sh
#
# This program does nothing
#

PID=$$
PGM=`basename $0`
TMP=/tmp/.$PGM.$PID

OPTS="abchx:y:z:-:"
SYNTAX=`echo $OPTS|sed "s/-://g"|sed "s/\(.*\)/[-\\1] [<args>]/g"|sed "s/\(.\):/] [-\\1 <value>/g"`
#sed "s/\(.\)/-\\1 /g"|sed "s/-:/<value>/g"
USAGE="$PGM $SYNTAX"


help() {
    usage
    echo
    echo "	-h display this help"
    echo "	-d debug mode"
    echo "	-q quiet mode"
    echo
    echo "sorry, helpman is in a minimalist mood"
    exit 0
}

usage() {
    echo "usage: $PGM $SYNTAX"
}

while getopts $OPTS PARAM
  do
    case $PARAM in
	"?")
	    ERROR=1
	    ;;
	-)
	    case $OPTARG in
		help)
		    help
		    ;;
		*)
		    printf $0: illegal option -- $OPTARG
#		    usage
	    esac
	    ;;
	x|y|z)
	    printf "$PARAM set to $OPTARG\n"
	    ;;
	h)
	    help
	    ;;
	d)
#		    echo "Debug mode"
	    STDERR="&1"
	    ;;
	q)
	    STDOUT="/dev/null"
	            ;;
	*)
	    VALUES="$VALUES $PARAM"
	    LASTVAL=$PARAM
    esac
done

shift `expr $OPTIND - 1`

if [ $ERROR ]
then
    usage
    echo "   type '$PGM --help' for more info"
    rm -f $TMP*
    exit $ERROR
fi

total=0
cat Cata/timetables.txt|while read date begin end
   do
   seconds=$(expr `date -d $end +%s` - `date -d $begin +%s`)
   hours=`expr $seconds / 36 / 25 \* 25`
   total=`expr $total + $hours`
   echo $date: $begin $end $hours|sed "s/\(..$\)/.\\1/"
   echo $total > /tmp/timetables.calc
   done
totalhours=`cat /tmp/timetables.calc`
amount=`expr $totalhours \* 375 / 10`
echo Total: $totalhours - $amount|sed "s/\([0-9][0-9]\>\)/.\\1/g"


rm -f $TMP*
