#!/bin/sh
#
# just for memory exit before doing it

exit

cat women.htm \
    | grep "img src" | sed "s/.*img src=//" \
    | cut -d '"' -f 2 \
    | while read file
  do 
  newname=`basename $file \
      | sed "s/\([0-9_\-]*\)\([a-zA-Z].*\)\(\..*\)/\\2-\\1\\3/" \
      | sed "s/-\././"`
  echo $newname 
  cp "$file" "../../../../../paradiso/women/$newname"
done