#!/bin/sh

if [ -f ~/.newsbot-rc ]
then
        . ~/.newsbot-rc
fi

#cd $MSGPATH

egrep ".* .*\..*(\(.*/.*\)|\[.*/.*\])" .getsubject | sed "s/\(.*\):.*Subj.* \(.*\)\.\(.*\)(/\\1 \\2.\\3(/" | sed "s/\(.*\):.*Subj.* \(.*\)\.\(.*\)\[/\\1 \\2.\\3\[/" | sed "s/).*/)/" | sed "s/(/ (/" | sed "s/  / /" | sed "s/<//" | sed "s/>//" | sed "s/\"//g" | grep "." | grep "/" > .getmultiples
