#!/bin/sh

ls|grep " "|while read spacedname
do
  mv "$spacedname" `echo $spacedname|sed "s/ /_/g"`
done

for SERIE in `ls $@|grep "[0-9]"|sed "s/[0-9]*\.[a-zA-Z]*$//"|sort -u|egrep -v "^$|^.$|^..$"`
  do 
  DIR=`basename $SERIE|sed "s/[-_]$//"`
  printf "$DIR: "
  NUMFILES=$((`ls $SERIE*|wc -l`))
  [ $NUMFILES -gt 1 ] && S=s || S=""
  printf "$NUMFILES file$S "
  mkdir -p ../Sorted/$DIR
  mv $SERIE* ../Sorted/$DIR && printf "moved to ../Sorted/$DIR"
  printf "\n"
done
