#!/bin/sh

if [ -f ~/.newsbot-rc ]
then
	. ~/.newsbot-rc
fi

INITIALPATH=$PWD

if [ ! -f ".getcount" ]
then
	newsbot-countparts
fi

FOLDERLIST=`grep "^>" .getcount | sed "s/^>//" | sed "s/ //g" | cut -d ":" -f 1`

echo "$PGM: Start `date`" >> $LOGFILE

for FOLDER in $FOLDERLIST
do
	echo -n "$FOLDER: "
	cd $INITIALPATH/$FOLDER
	echo -n "Decoding `grep -c "" .getlist` parts to $BINPATH/$FOLDER... "
	cat .getlist | xargs cat | \
		uudecode -o $BINPATH/$FOLDER 2>/dev/null \
		&& RESULT=1 || RESULT=0
	if [ $RESULT ]
	then
		echo -n "Done "
		if [ -f "$BINPATH/$FOLDER" ]
		then
			echo "$PGM: Decoded $FOLDER" >> $LOGFILE
			DECODED="$DECODED $FOLDER"
			rm -rf $INITIALPATH/$FOLDER/
		else
			mv $INITIALPATH/$FOLDER/ $NEWSPATH/Errors/
			echo -n "without result"
			echo "$PGM: Error $FOLDER produced no result" >> $LOGFILE
		fi
		echo
	else
		echo "An error occurred"
	fi
done

echo "$PGM: End `date`" >> $LOGFILE

