#!/bin/sh

if [ -f ~/.newsbot-rc ]
then
        . ~/.newsbot-rc
fi

cd $MSGPATH

ATTACHLIST=`cut -d " " -f 2 .getmultiples | sort -u`

echo "$PGM: Start `date`" >> $LOGFILE 
for NAME in $ATTACHLIST
do
NAMELIST=`grep " $NAME " .getmultiples | cut -d " " -f 1`
EXT=`echo $NAME | sed "s/.*\.//"`
echo -n "$NAME: "
#if [ -d "$ATTACHPATH/$EXT" ]
#then
#	echo Accepted
	echo "$PGM: Moved $NAME to $ATTACHPATH" >> $LOGFILE
	mkdir -p $ATTACHPATH/$NAME
	rm -f $ATTACHPATH/$NAME/.get*
	mv $NAMELIST $ATTACHPATH/$NAME
#else
#	echo Rejected
#	echo "$PGM: Deleted $NAME" >> $LOGFILE
#	rm -f $NAMELIST 
##	mkdir -p $REJECTPATH/$EXT/$NAME
##	mv $NAMELIST $REJECTPATH/$EXT/$NAME
#fi
done
echo "$PGM: End `date`" >> $LOGFILE
