#!/bin/sh

if [ -f ~/.newsbot-rc ]
then
        . ~/.newsbot-rc
fi

cd $MSGPATH

echo -n Extracting subjects from `ls *-* | grep -c ""` messages... ""
$PGMPATH/newsbot-mklist-subjects
echo Done.
echo
echo -n "Selecting multipart messages... "
$PGMPATH/newsbot-mklist-multiples
echo Done.
echo
echo "Moving multiparts to folders... "
echo
$PGMPATH/newsbot-folderize | grep Accepted | cut -d ":" -f 1
echo
echo Counting complete sets
echo
cd $ATTACHPATH
$PGMPATH/newsbot-countparts 2>/dev/null 
echo
echo Done.
echo
echo Decoding complete sets
echo
$PGMPATH/newsbot-decode 2>/dev/null
