#!/bin/sh

PGM=`basename $0`
TMP=/tmp/$PGM.$$
LOG=/tmp/$PGM.log

NEWSSERVER=news.kpn.be
REMOTESERVER=tourteau
REMOTEDIR=/home/ovh/news
REMOTEMSG=$REMOTEDIR/Msgs
NEWSCLIENT=/home/ovh/bin/suck
LOCALDIR=/data/news
LOCALMSG=$LOCALDIR/Msgs
LOCALDEC=$LOCALDIR/Decoded

ssh $REMOTESERVER $NEWSCLIENT $NEWSSERVER -dd $REMOTEDIR -dm $REMOTEMSG -C 100 -m 2>$TMP.suck-errors &

SUCKID=$!
echo $SUCKID

ps -ef|grep "suck"|grep -v grep

RUNNING=yes

(
while [ "$RUNNING" = "yes" ]
do
  echo "$PGM still running at `date`"
  rsync -e ssh -avz $REMOTESERVER:$REMOTEMSG/ $LOCALMSG/
  last=`ls $LOCALMSG|tail -2|head -1`
  if [ "$last" ]
      then
      messages=`ssh $SERVER ls $REMOTEMSG/*|grep -B 1000 $last`
      ssh tourteau rm $messages
      cd $LOCALDEC
      for file in $LOCALMSG/*
	do
	uudecode $file && rm $file 2>/dev/null || mv $file $LOCALDIR/Errors/
      done
  fi
  sleep 10
done
) &

WHILEID=$!

wait $SUCKID 
unset RUNNING
kill $WHILEID
