#!/bin/sh

echo "You silly why don't you use 'sed -i'?"
sed -i "~" $@

exit


SOURCEDIR=$1
FILEPATTERN=$2
MATCH=$3
REPLACE=$4

PGM=`basename $0`
TMP="/tmp/$PGM.$$"


if [ ! "$4" ]
	then
	echo "usage: $PGM <dir> <filepattern> <sourcepattern> <string>"
	exit 1
fi

echo "scanning folder $1"
echo "for files $2"
echo "replacing $3"
echo "by" "$4"


find $SOURCEDIR -type f -name "$FILEPATTERN" \
| while read file
	do 
	#echo "$file"
	egrep "$MATCH" "$file" >/dev/null 2>/dev/null  && echo "$file" \
	| while read matchedfile
	do
		printf "processing $matchedfile "
		cat "$matchedfile" | tr "
" "\n" | sed "s/$MATCH/$REPLACE/g" > "$TMP" 
		result=$?
		if [ $result -ne 0 ]
			then
			echo "error $result"
			exit 1
		fi
#		mv "$TMP" "$matchedfile"
		result=$?
		if [ $result -ne 0 ]
			then
			echo "error $result"
			exit 2
		fi
		echo "ok"
	done
done

