#!/bin/sh

src="$@"

for folder in *F PajamaF
  do
  ls $folder/*.skn 2>/dev/null
done | sort \
    | while read path
  do
  skin=`basename $path .skn`
#  srcskin=`printf "$(head -1 "$src")"`
  srcskin=`head -1 "$src" | tr "" "\n"`
  echo "# $srcskin > $path"
  cat "$src" \
      | sed "s/$srcskin/$skin/" \
      > $path
done


exit


srcname=`head -1 "$src"`

for folder in B *F PajamaF
  do ls $folder/*.skn 2>/dev/null
done | sort | while read file
  do skin=`basename "$file" .skn`
  echo "# $skin"
#  cat "$src" | sed "s/$srcname/$skin/" > "$file"
  cp "$src" "$file"
done


