#!/bin/sh

srcdir=src
model=PajamaM

if [ "$1" = "-u" ]
    then
    sizes=unique
    shift 1
else
    sizes="Fat Fit Skn"
fi

for newskin in $@
do
  echo "# make $newskin"
  for size in $sizes
    do
    if [ $size = "unique" ] 
	then
	unset size
    fi
    dstdir=$newskin
    if [ ! -d "$dstdir" ]
	then
	mkdir $dstdir || exit 1
    fi

    cmx=${newskin}${size}_01
    skn="xskin-$cmx-PELVIS-BODY"
    srccmx=${model}_01
    srcskn=xskin-$srccmx-PELVIS-BODY
    printf "$cmx.cmx "
    cat $srcdir/$srccmx.cmx \
	| sed "s/$srccmx/$cmx/" \
	> "$dstdir/$cmx.cmx" && printf "ok"
    echo
    printf "   $skn.skn "
    cat $srcdir/$srcskn.skn \
	| sed "s/$srccmx/$cmx/" \
	> "$dstdir/$skn.skn" && printf "ok"
    echo
    for color in drk lgt med
      do 
      printf "   $newskin$size$color_01.bmp "
      cp "$srcdir/$model${color}_01.bmp" "$dstdir/$newskin$size${color}_01.bmp" \
	  && printf "$ok"
      echo
    done
  done
  echo
done