#!/bin/sh

setenv DISPLAY localhost:0
setenv DYLD_LIBRARY_PATH /Applications/OpenOffice.org1.0.3/program:/Applications/OpenOffice.org1.0.3/program/filter:/usr/X11R6/lib
cd /Applications/OpenOffice.org1.0.3/program
sh soffice
