#!/bin/sh

ACTION=compare
ORIGDIR=/maryse

PGM=`basename $0`

echo `date` - $PGM begin in $ACTION mode
echo

if [ "$1" ]
then
    LOCALDIR=$1
else
    echo "$PGM: no directory specified, using current dir..."
    LOCALDIR=$PWD
fi

echo "   $LOCALDIR"

case $ACTION in
    restore)
	echo $PGM: No tape specified, scanning devices...
	for DEVICE in /dev/rmt/*cn
	  do
	  TAPESTATUS=
	  TAPE=$DEVICE
	  export TAPE
	  printf "%s" "   $DEVICE "
	  TAPESTATUS=`mt status 2>/dev/null |head -1|grep DLT`
	  printf "%s" "$TAPESTATUS"
	  if [ "$TAPESTATUS" ]
	      then
	      TAPES="$TAPES $DEVICE"
	      printf "%s" " selected"
	  fi
	  printf "%s\n"
	done
	for TAPE in $TAPES
	  do
	  RESTOREDIR=$LOCALDIR/`basename $TAPE`
	  mkdir $RESTOREDIR
	  cd $RESTOREDIR
	  
	  export TAPE
	  echo "$PGM: Restoring"
	  echo "   from $TAPE"
	  echo "   to   $RESTOREDIR"
	  echo "`date` - mt rew"
	  mt rew
	  RC=$?
	  echo "   return code: $RC"
	  
	  if [ $RC != 0 ]
	      then
	      echo "out after mt rew on $TAPE" 
	  else
	      echo "`date` - /usr/sbin/ufsrestore rfb $TAPE 100"
	      /usr/sbin/ufsrestore rfb $TAPE 100
	      
	      RC=$?
	      echo "   return code: $RC"
	      if [ $RC != 0 ]
		  then
		  echo "   failed"
	      else
		  echo "`date` - mt -f $TAPE rew"
		  mt -f $TAPE rew
		  RC=$?
		  echo "   return code: $RC"
		  
		  if [ $RC = 0 ]
		      then 
		      echo "`date` `host` $PGM finished successfully"
		  else
		      echo "`date` `host` $PGM finished with errors"
		  fi
	      fi
	  fi
	done
	;;
    compare)
	SUMERRORS=0
	DIFFERRORS=0

	cd $LOCALDIR
	for FOLDER in $LOCALDIR/*
	  do
	  if [ -d $FOLDER ]
	      then
	      echo `date` $PGM: scanning $FOLDER
	      cd $FOLDER
	      find . -type f|grep -v "./restoresymtable"|sed "s/^\.//"\
		  | while read FILE
		do
		BACK=$FOLDER$FILE
		ORIG=$ORIGDIR$FILE
		BACKSUM=`sum "$BACK"|cut -d " " -f 1,2`
		ORIGSUM=`sum "$ORIG"|cut -d " " -f 1,2`
		DIFF=`diff "$BACK" "$ORIG"`
		if [ "$BACKSUM" != "$ORIGSUM" ]
		    then
		    echo $FILE: incorrect sum
		    SUMERRORS=`expr $SUMERRORS + 1`
		fi
		if [  "$DIFF" ]
		    then
		    echo $FILE: diff makes a result
		    DIFFERRORS=`expr $DIFFERRORS + 1`
		fi
		
#		echo $FILE
	      done
	      echo `date` - $PGM: end of $FOLDER scan
	  fi
	done
	echo $SUMERRORS sum errors
	echo $DIFFERRORS diff errors
esac
