#!/bin/sh

export PATH=$(dirname "$0"):$PATH

string=`echo $@ \
	| tr [:upper:] [:lower:] \
	| tr "áàâäéèêëíìîïóòôöúùûüç" "aaaaeeeeiiiioooouuuuc" \
	| sed "s/[œŒ]/oe/g" \
	| urlcoder -e \
	| sed "s/%26/,/g" \
	| sed "s/+/ /g" \
	| sed "s/ ,/,/g" \
	| sed "s/\%[A-Z0-9][A-Z0-9]//g"
`

# | tr "ÁÀÂÄÉÈÊÊÍÌÎÏÓÒÔÖÚÙÛÜÇ" "AAAAEEEEIIIIOOOOUUUUC" \

/usr/bin/python -c "import sys; print sys.argv[1].title()" "$string" \
	| sed "s/ \././g" \
	| sed "s/  */ /" \
	| sed "s/\.Mov/.mov/" \
	| sed "s/\.Jpg/.jpg/" 

#echo "$string"

# /usr/bin/python -c "import sys; print sys.argv[1].title()" "$1" \
