#!/bin/bash
#
# Copyright 2015 Olivier van Helden <olivier@van-helden.net>
# Released under GNU Affero GPL v3.0 license
#    http://www.gnu.org/licenses/agpl-3.0.html

evoice=mb/mb-fr4
mvoice=fr4
pitch=55
speed=140

TTS=$(which say) || TTS=$(which mbrola) || TTS=$(which espeak) || TTS=cat
TTS=$(basename "$TTS")
PLAYER=$(which paplay) || PLAYER=$(which aplay) || PLAYER=$(which mplayer)

[ "$@" ] || exit
string="$@"

case $TTS in 
    say)
	say "$string"
	;;
    espeak)
	espeak -v $evoice -s $speed -p $pitch "$string"
	;;
    mbrola)
	[ -f "$mvoice" ] || mvoice=/usr/share/mbrola/$mvoice/$mvoice
	espeak -v $evoice -s $speed -p $pitch "$string" --pho \
	    | mbrola $mvoice - -.au | paplay >/dev/null 2>/dev/null
	;;
    *)
	echo "$string"
	;;
esac


