#!/bin/sh
#
# Copyright 2015 Olivier van Helden <olivier@van-helden.net>
# Released under GNU Affero GPL v3.0 license
#    http://www.gnu.org/licenses/agpl-3.0.html

OS=`uname -a | cut -d " " -f 1 | sed "s/[^a-zA-Z0-9]//g"`

if [ "$1" ]
	then
	for name in "$@"
	do
		echo "$name"
	done
else
	cat
fi | while read name
do
    if [ "$OS" = "Darwin" ]
    then
	echo "$name" \
	    | tr ", áàâäéèêëíìîïóòôöúùûüçñ" "__aaaaeeeeiiiioooouuuucn" \
	    | sed "s|[\`´'^]||g"
    else 
	echo "$name" \
	    | iconv -f utf-8 -t ascii//translit
    fi | tr " [:upper:]" "_[:lower:]" \
	| sed "s|[^a-zA-Z0-9_\./-]*||g" \
	| sed "s|__*|_|g" \
	| sed "s/_*--*_*/-/g"
done

	 # \
	 #  	| tr "\n" "_" | sed "s|__*|_|g" | sed "s|_$||g"
