#!/bin/sh

IFS='|'

cat "$@" \
    | grep "[0-9]* *km" \
    | while read id name distance1 distance2 distance3
  do
  printf "[$id] $name: "
  city1_name=`echo $distance1 | sed "s/ *[0-9]* km.*//`
  city1_dist=`echo $distance1 \
      | sed "s/^[^0-9]*//" \
      | sed "s/[^0-9]*$//" \
      | grep -v "[^0-9]" `
  city1_dir=`echo $distance1 | cut -d '(' -f 2 | cut -d ')' -f 1 \
      | sed "s/nord-est/2/" \
      | sed "s/sud-est/4/" \
      | sed "s/sud-ouest/6/" \
      | sed "s/nord-ouest/8/" \
      | sed "s/nord/1/" \
      | sed "s/est/3/" \
      | sed "s/sud/5/" \
      | sed "s/ouest/7/" \
      | grep -v "[^0-9]"
      `
  printf "$city1_name $city1_dist $city1_dir "
  city2_name=`echo $distance2 | sed "s/ *[0-9]* km.*//`
  city2_dist=`echo $distance2 \
      | sed "s/^[^0-9]*//" \
      | sed "s/[^0-9]*$//" \
      | grep -v "[^0-9]" `
  printf "$city2_name $city2_dist $city2_dir "
  city3_name=`echo $distance3 | sed "s/ *[0-9]* km.*//`
  city3_dist=`echo $distance3 \
      | sed "s/^[^0-9]*//" \
      | sed "s/[^0-9]*$//" \
      | grep -v "[^0-9]" `
  printf "$city3_name $city3_dist $city3_dir "
  if [ ! "$city1_dist " ]
      then
      echo ' ERROR'
      break
  fi
  psql -d lemaire <<EOF 
UPDATE cities SET
      city1_name='$city1_name',
      city1_dist='$city1_dist',
      city1_dir='$city1_dir',
      city2_name='$city2_name',
      city2_dist='$city2_dist',
      city3_name='$city3_name',
      city3_dist='$city3_dist'
      WHERE city_id='$id'
EOF
done