#!/bin/sh

IFS='|'

#    DISTINCT on (c.guide_id, a.lang)

restos=`(
    psql -Atq -d lemaire <<EOF
    SELECT
    DISTINCT on (c.guide_id)
    c.guide_id, c.name, a.lang, a.modlogin, a.modstamp, a.comment_id
    FROM comments as a, companies as c
    WHERE c.company_id=a.company_id AND a.edition=2005
    ORDER BY c.guide_id, a.lang, a.modstamp
EOF
) | wc -l|sed "s/ //g"`

echo "## $restos restos with at least 1 comment"
echo

(
    psql -Atq -d lemaire <<EOF
    SELECT
    c.guide_id, c.name, a.lang, a.modlogin, a.modstamp, a.comment_id
    FROM comments as a, companies as c
    WHERE c.company_id=a.company_id AND a.edition=2005
    ORDER BY c.guide_id, a.lang, a.modstamp
EOF
) | sed "s/ *|/|/g" | while read id name lang author date commentid
  do 
  if [ ! "$id" = "$oldi" ]
      then 
      echo "$id $name"
      oldl=""
  fi
  printf "\t"
  if [ ! "$lang" = "$oldl" ]
      then
      printf "$lang"
  fi
  printf "\t$date\t$author\n"
  oldl=$lang
  oldi=$id
done
