#!/bin/sh

STAMP=`date +"%Y%m%d-%H%M%S"`
PGM=`basename $0 .sh`
SERVER=duke
DB=lemaire
DST=~/backup

if [ ! -d "$DST" ]
    then
    mkdir -p "$DST" 
    result=$?
    if [ $result -gt 0 ]
	then
	echo Could not create "$DST"
	exit $result
    fi
fi

ssh $SERVER pg_dump -C -d lemaire > "$DST/$DB-$STAMP-dump"
