#!/bin/sh

IFS='|'

(
psql -Atq -d lemaire <<EOF
SELECT company_id, guide_id, city, name
FROM companies 
WHERE guide_id ~ '-' 
   AND guide_id !~ '^000-'
   AND name != ''
ORDER BY guide_id
;
EOF
) | while read company_id guide_id city name
  do
  city_id=`echo $guide_id|cut -d "-" -f 1`
  if [ "$city_id" != "$lastcity_id" ]
      then
      echo "Now in $city_id $city" >&2
  fi
  echo "   $name" >&2
  echo "UPDATE companies SET city_id='$city_id' WHERE company_id='$company_id';"
  lastcity_id=$city_id
done | psql -d lemaire > /dev/null





