#!/bin/sh

IFS='|'

if [ ! "$2" ]
then
    if [ ! $1 ]
	then
	exit
    fi
    name=$1
    psql -Atq -d lemaire -c "select city_id, name from cities 
    where name ~* '$name';" | while read city_id name
      do
      echo $city_id $name
    done
else
    echo "UPDATE cities SET 
    city1_name='$2', 
    city1_dist='$3',
    city1_dir='$4',
    city2_name='$5',
    city2_dist='$6',
    city3_name='$7',
    city3_dist='$8'
    WHERE city_id='$1'" | psql -d lemaire
fi
