#!/bin/sh

IFS='|'

cat $@ | sed "s/	/|/g" | while read name page
  do
  for prefix in "LÕ" "L'" "Õt " "Ë la " "Ë " "Une " "Un " "The " "LÕ " "Les " "Le " "La " "In Õt " "In het " "In de " "In " "Het " "DÕ" "Den " "De " "Aux " "Au " "Al " "@ " "[[0-9]* "
	do
    name=`echo $name | sed "s/^\($prefix\)\(.*\)/\\2 (\\1)/" \
	| sed "s/ )/)/" | sed "s/) (/ /g"`
done
  printf "$name \t $page\n"
done


