#!/bin/sh

IFS='|'
thiscity="000-000"
thisprov="000-000"

(
psql -Atq -d lemaire <<EOF
SELECT guide_id, city_id, name, company_type, street, company_id
FROM companies
ORDER by guide_id;
EOF
) | sed "s/ *\|/\|/g" | while read guide_id city_id name company_type street company_id
  do
  company_type=`echo $company_type|sed "s/ //g"`
  update=true
  if [ $company_type = "Ville" -a "$guide_id" ]
      then
      thiscity=$guide_id
      printf "City: $thiscity $street "
  elif [ $company_type = "Province" -a "$guide_id" ]
      then
      thisprov=$guide_id
      printf "Province: $thisprov $street "
  elif [ "$company_id" ]
      then
      printf "   $guide_id $thiscity $thisprov $name"
  else
      update=false
  fi
  if [ $update=true ]
      then
      echo "UPDATE companies 
      SET city_id='$thiscity', prov_id='$thisprov'
      WHERE company_id='$company_id'"|sed "s/ *\'/\'/g" \
	  | psql -Atqd lemaire && echo " - OK" || echo " - Errror"
  fi
done

