#!/usr/bin/bash


PGM=`basename $0`
IFS='|'
TMP=/tmp/$PGM.$$

provid=$1
lang=$2
dest=$3
mailto=$4

if [ ! "$provid" ]
    then
    echo usage: $PGM prov_id lang_orig lang_dest >&2
    (
	cat <<EOF
	SELECT prov_id, name
	FROM companies 
	WHERE company_type='Province'
	ORDER BY guide_id;
EOF
    ) | psql -Atq -d lemaire |sed "s/ *|/ /g"
    exit 1
fi

if [ ! "$dest" ]
    then
    echo usage: $PGM prov_id lang_orig lang_dest >&2
    exit 2
fi

if [ "$mailto" ]
    then
    (
	cat <<EOF
Date: `date`
From: robot@guide-lemaire.com
To: $mailto
Reply-To: olivier@van-helden.net
Subject: commentaires relus en $lang


EOF
    ) > $TMP
fi

(
cat <<EOF
	    SELECT company_id, guide_id, city_id, name, points, diamonds, nc
    FROM companies
    WHERE prov_id='$provid' 
          AND publish=true 
	  AND comment_status_$lang=3
	  AND comment_status_$dest=0
    ORDER BY prov_id, city_id, points desc, diamonds desc, nc;
EOF
) | psql -Atq -d lemaire \
    | sed "s/ *|/|/g" \
    | while read company_id guide_id city_id name points diamonds nc
  do
  if [ "$city_id" != "$oldcity" ]
      then
      echo
      echo "----------------------------------------"
      city=`psql -Atq -d lemaire -c "SELECT name FROM cities WHERE city_id='$city_id'"`
      echo "$city ($city_id)"
      echo "----------------------------------------"
  fi
  oldcity=$city_id
  echo
  echo "[$guide_id] $name"
  echo
  (
      cat <<EOF
      SELECT comment FROM comments 
      WHERE  company_id='$company_id' 
      AND lang='$lang'
      AND edition=2005
      ORDER BY comment_id desc
      LIMIT 1
EOF
  ) | psql -Atq -d lemaire 
done >> $TMP

if [ "$mailto" ]
    then
    cat $TMP | sendmail -t
else
    cat $TMP
fi

rm $TMP