#!/bin/sh

IFS='|'
(
psql -Atq -d lemaire <<EOF 
SELECT holiday_id, comment from holidays 
WHERE comment ~* 'nouvel.*an|carnaval'
EOF
) | while read id comment
  do 
  printf "$id\t$comment "
  comment=`echo $comment|sed 's/[Nn]ouvel[- ]*[Aa]n/Nouvel An/g'`
  comment=`echo $comment|sed 's/Carnaval/carnaval/g'`
  comment=`echo $comment|sed "s/\'/\\\\\'/g"`
  psql -d lemaire -c "UPDATE holidays SET comment='$comment' WHERE holiday_id='$id';"
  printf "\t"
  psql -Atq -d lemaire -c "SELECT holiday_id, comment from holidays WHERE holiday_id='$id'"| cut -d "|" -f 2- 
done

exit

psql -Atq -d lemaire <<EOF 
SELECT holiday_id, comment from holidays 
WHERE comment ~* 'nouvel.*an|carnaval'
ORDER BY holiday_id
EOF
