#!/bin/sh

for DOMAIN in $@
do
	DOMAIN=`echo $DOMAIN | sed "s/www\.//"`
	SERVERS=$(echo -n `host -t ns $DOMAIN 2>/dev/null | grep "^$DOMAIN name server" | sed "s/.*server //"`)
	if [ -z $SERVERS ]
		then
		ERROR="no server found"
		OTHERDOMAIN=`echo $DOMAIN | sed "s/.*\.\(.*\)\.\(.*\)/\\1.\\2/"`
		echo $DOMAIN: $OTHERDOMAIN
	else
		ERROR=""
		OTHERDOMAIN=""
	fi
done
