#!/bin/sh

cat $@ | while read name
  do   printf "$name\n"  
  whois -Q $name.com | grep "^No match for" >/dev/null 2>/dev/null \
      && printf "\t$name.com\n" 
  whois -Q $name.net | grep "^No match for" >/dev/null 2>/dev/null \
      && printf "\t$name.net\n" 
#  whois -Q $name.be | grep "^Status:.*FREE" >/dev/null 2>/dev/null \
#      && printf "\t$name.be\n"
#  sleep 1
done 

