#!/bin/sh
. /etc/dnsbot/dnsbot-rc

echo "For security, execution of this program is disabled"
exit 1

for DOMAIN in $DOMAINS
do
	echo "From: <dnsadmin@qwentes.be>" > $TMPFILE.mail
	echo "To: <$MAILBOT>" >> $TMPFILE.mail
	echo "Bcc: <dnsadmin@qwentes.be>" >> $TMPFILE.mail
	echo "Subject: Delete request $DOMAIN" >> $TMPFILE.mail
	echo >> $TMPFILE.mail
	AGENTREF=$DOMAIN
	cat $TEMPLATES/DEL-DOMAIN \
		| sed "s/\[DOMAIN\]/$DOMAIN/" \
		| sed "s/\[DATE\]/$DATE/" \
		> $TMPFILE
	MDSTRING="$PASSPHRASE `cat $TMPFILE`"
	echo $PASSPHRASE > $TMPFILE.md5
	cat $TMPFILE >> $TMFILE.md5
	SIGNATURE=`(echo $PASSPHRASE; cat $TMPFILE) | awk '{gsub("[ \f\r\n\0]",""); printf $0;}' | md5sum | cut -c 1-32`
	cat $TEMPLATES/AUTHENTICATION \
		| sed "s/\[AGENTID\]/$AGENTID/" \
		| sed "s/\[AGENTREF\]/$AGENTREF/" \
		| sed "s/\[SIGNATURE\]/$SIGNATURE/" \
		>> $TMPFILE
	cat $TMPFILE.mail $TMPFILE | /usr/sbin/sendmail -t
	echo Sent delete request for $DOMAIN
done

rm -f $TMPFILE*

