#!/bin/sh

CONFFILE=/etc/named.conf

DOMAINS=`sed "s/^ *//" $CONFFILE | grep -w "^zone" | cut -d '"' -f 2`
DOMAINPATH=`grep "option.*directory" $CONFFILE | sed "s/.*directory \"\(.*\)\".*/\\1/"`

for DOMAIN in $DOMAINS
do
	DOMAININFO=`grep "zone \"$DOMAIN\"" $CONFFILE`
	DOMAINFILE=`echo $DOMAININFO | cut -d '"' -f 4`
	DOMAINAUTH=`echo $DOMAININFO | sed "s/.*masters//" | sed "s/[{} ]//g" | cut -d ";" -f 1`
	DOMAINTLD=`echo $DOMAIN | sed "s/.*\.//"`
	case $DOMAINTLD in 
	be)
		DOMAINNS=`host -t ns $DOMAIN ns.eu.net | grep -w "name server" | cut -d " " -f 4`
		;;
	info)
		DOMAINNS=`whois -h whois.networksolutions.com $DOMAIN | grep -A 5 "Domain servers" | grep -v "Domain servers" | sed "s/^ *//" | egrep "[a-zA-Z0-9]" | cut -f 1`
		;;
	*)
		DOMAINNS=`whois $DOMAIN | sed "s/ *//g" | grep "^NameServer:" | cut -d ":" -f 2`
	esac
	echo $DOMAIN:$DOMAINAUTH:$DOMAINTLD:$DOMAINNS
# `named-xfer -f $DOMAINPATH/$DOMAINFILE -z $DOMAIN $DOMAINAUTH 2>&1 | cut -d ":" -f 2`
done
