#!/bin/sh

NAMEDCONF=/etc/named.conf
NAMEDDIR=/var/named/sec
NS=cagliostro.qwentes.be

if [ "$1" ]
then
    echo Using given domains
    DOMAINS="$@"
else
    echo Using conf file domains
    DOMAINS=`sed "s/^ *//" $NAMEDCONF | grep -w "^zone.*slave" \
	| cut -d '"' -f 2`
fi

for DOMAIN in $DOMAINS
do
    echo -n "$DOMAIN: "
    echo -n `named-xfer -z $DOMAIN -f $NAMEDDIR/$DOMAIN $NS 2>&1 \
	| cut -d ":" -f 2-`
    echo
    CHANGES=YES
done

if [ "$CHANGES" ]
then
    echo -n "Changes were made - reloading named config... "
    echo -n `/usr/sbin/ndc reload`
    echo
fi



