#!/bin/sh
# Adds standard domain entry to /etc/named.conf

CONFFILE=/etc/named.conf
DEFCONF="parking"
MASTER=172.16.66.55
# SECSERVERS="houdini.qwentes.be oz.qwn.be"

for DOMAIN in $@
do
	DOMAINEXISTS=`grep "zone \"$DOMAIN\"" $CONFFILE`
	if [ "$DOMAINEXISTS" ]
	then
		echo "$DOMAIN: already in $CONFFILE"
	else 
		CONFMODIFIED=yes
		if [ "$MASTER" ]
		then
			echo "zone \"$DOMAIN\" { type slave; file \"sec/$DOMAIN\"; masters { $MASTER ;};};" >> $CONFFILE
			echo "$DOMAIN: added as slave" 
		else
			echo "zone \"$DOMAIN\" { type master; file \"$DEFCONF\";};" >> $CONFFILE
			echo "$DOMAIN: added as master" 
		fi
	fi
done
if [ "$CONFMODIFIED" ]
then
	echo -n "Modification were made to $CONFFILE... "

	if [ -f "/usr/sbin/rndc" ]
	then
	    echo -n "Reload initiated "
	    echo -n `/usr/sbin/rndc reload >/dev/null 2>&1 \
		|| /usr/bin/killall -HUP named`
	elif [ -f "/usr/sbin/ndc" ]
	then
	    echo -n `/usr/sbin/ndc reload`
	fi

	echo
fi

#for SERVER in $SECSERVERS
#do
#	echo adding configuration also to $SERVER
#	ssh $SERVER $0 $@
#done
