#!/bin/sh

PGM=`basename $0`
LOCK=~/.$PGM.lock

USER=mff
MAC=0:30:65:10:bb:5a
AGEMAX=10               ## in minutes

help() {
    usage
    echo
    echo "-h display this help"
    echo "-f|--force ignore age of last update"
    echo "-a         minimum delay between two updates"
    echo "-i         ip address"
    echo "-m         mac address (will find IP with arp values"
    echo "-u         user name"
    echo
    exit 0
}

usage() {
    echo "usage: $PGM [-hdq] [-i <ip>|-m <mac address>] \\"
    echo "            [-u <user>] [-a <age max>]"
}


for PARAM in $@
do
    if [ $NEXTPARAM ]
    then
	echo $NEXTPARAM=$PARAM | sh
	NEXTPARAM=
    else
	case $PARAM in
	--help)
	    help
	    ;;
	--force)
	    FORCE=yes
	    AGEMAX=0
	    ;;
	-*)
	    for PARAM in `echo $PARAM|sed "s/-//g"|sed "s/\(.\)/ \1/g"`
	    do
		case $PARAM in
		h)
		    help
		    ;;
		d)
		    STDERR="&1"
		    ;;
		q)
		    STDOUT="/dev/null"
		    ;;
		f)
		    FORCE=yes
		    AGEMAX=0
		    ;;
		i)
		    NEXTPARAM=IP
		    ;;
		m)
		    NEXTPARAM=MAC
		    ;;
		u)
		    NEXTPARAM=USER
		    ;;
		a)
		    NEXTPARAM=AGEMAX
		    ;;
		*)
		    ERROR=1
		    echo "wrong parameter -$PARAM"
		esac
	    done
	    ;;    
	*)
	    VALUES="$VALUES $PARAM"
	    LASTVAL=$PARAM
	esac
    fi
done

if [ "$MAC" ]
then
    IP=`grep $MAC /var/arpwatch/arp.dat|tail -1|cut -f 2`
fi

if [ ! "$IP" ]
then
    ERROR=2
    echo "No IP address provided or IP not found"
fi

if [ $ERROR ]
then
    usage
    echo "   type '$PGM --help' for more info"
    rm -f $TMP*
    exit $ERROR
fi

if ! (ping -w 2 -c 1 $IP >/dev/null 2>&1)
then
    if [ -f $LOCK ]
    then
	cat $LOCK >> $LOCK.history 
	rm -f $LOCK
    fi
    exit 3
fi

if [ -f $LOCK ]
then
    DELTAMAX=$(($AGEMAX*60))
    DELTA=$((`date +%s` - `stat -t $LOCK|cut -d " " -f 13`))
    if [ $DELTA -lt $DELTAMAX ]
    then
	exit 4
    fi
fi

echo $IP `date` >> $LOCK

DEST=/.1/.james
mkdir -p $DEST

#cat $LOCK

rsync -e ssh -W -avz root@$IP:~$USER/Desktop/Brol $DEST |egrep -v "^receiving|^wrote|^total"
rsync -e ssh -W -avz root@$IP:"~$USER/Documents/Eudora\ Folder/Mail\ Folder" $DEST/ |egrep -v "^receiving|^wrote|^total"

#scp -rp root@$IP:~$USER/Desktop/Brol/D.K.D./ ./Brol/ && echo Docs OK || echo Docs error
#scp -rp root@$IP:"~mff/Documents/Eudora\ Folder/Mail\ Folder/" ./ && echo Mail OK || echo Mail error
#scp -rp root@$IP:~$USER/.Trash ./
#scp -rp root@$IP:~$USER/Desktop/Brol/ ./

